Ansible 4
Otus-DevOps-2021-08/GrigoriyKochenyatov_infra pull request #9
Opened 2022-01-11 18:25 UTC by GrigoriyKochenyatov

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-01-12 09:46 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу, дз возвращаю на доработку
Если что оформляйте еще один пуллреквест и добавляйте туда свои вопросы =)

2022-01-12 09:46 UTC, mrgreyves commented on ansible/Vagrantfile
> +ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Нужно еще раз проверить этот файл

2022-01-12 09:46 UTC, mrgreyves commented on ansible/Vagrantfile
> +      ansible.extra_vars = {
Думаю стоит добавить переменных исходя из методички =)

2022-01-13 19:08 UTC, GrigoriyKochenyatov commented
добрый вечер, Владимир.
Никак не получается пройти этап с molecule verify

Делал все по методичке. 

`venv) [grigoriy@fedora db]$ molecule verify 
--> Test matrix
    
└── default
    └── verify
    
--> Scenario: 'default'
--> Action: 'verify'
--> Executing Testinfra tests found in /home/grigoriy/otus/GrigoriyKochenyatov_infra/ansible/roles/db/molecule/default/tests/...
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.11.0, pluggy-0.13.1
    rootdir: /home/grigoriy/otus/GrigoriyKochenyatov_infra/ansible/roles/db/molecule/default
    plugins: testinfra-1.7.1
collected 0 items / 2 errors                                                   
    
    ==================================== ERRORS ====================================
    ____________________ ERROR collecting tests/test_default.py ____________________
    tests/test_default.py:6: in <module>
        os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
    ../../../../venv/lib/python2.7/site-packages/testinfra/utils/ansible_runner.py:152: in __init__
        self.cli = ansible.cli.playbook.PlaybookCLI(None)
    ../../../../venv/lib/python2.7/site-packages/ansible/cli/__init__.py:61: in __init__
        raise ValueError('A non-empty list for args is required')
    E   ValueError: A non-empty list for args is required
    _________________ ERROR collecting tests/test_default copy.py __________________
    tests/test_default copy.py:6: in <module>
        os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
    ../../../../venv/lib/python2.7/site-packages/testinfra/utils/ansible_runner.py:152: in __init__
        self.cli = ansible.cli.playbook.PlaybookCLI(None)
    ../../../../venv/lib/python2.7/site-packages/ansible/cli/__init__.py:61: in __init__
        raise ValueError('A non-empty list for args is required')
    E   ValueError: A non-empty list for args is required`

Уже разные варианты испробовал.
Ubuntu не могу как родительскую ОС, т.к наглухо виснет, хорошо работает Fedora 35
Связка питон2.7 через venv, остальное видно в requirements
Ставил конечно из виртуального окружения.

Такое ощущение что локальная бага import testinfra.utils.ansible_runner

Попробовал такую связку - все-равно ошибка
ansible>=2.4
molecule==2.17.0
testinfra==1.14.1
python-vagrant>=0.5.15

2022-01-19 14:47 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, порой наши окружения все такие не идеальны
Можно наловить весьма своеобразных вещей

2022-01-20 17:09 UTC, merged